### ISSUE TITLE
ask your questions (in French)

### ISSUE THREAD

**Issue by ClementineCttn** [covprehension/CoVprehension#12]
Dans la version EN, "ask your questions" renvoyait vers le formulaire en anglais https://framaforms.org/covprehension-challenge-us-ask-your-questions-1585581105 mais aujourd'hui il pointe vers le formulaire en français

**Comment by RoiArthurB** [comment]
Fixed here 8a74089163b868b435a867f24e9f0c96c4da134b
You have an input in every `<lang>.yml` to set a proper custom form URL ;)
