### ISSUE TITLE
about with pics in english?

### ISSUE THREAD

**Issue by ClementineCttn** [covprehension/CoVprehension#14]
la version EN du about apparaît en français et sans images :(

**Comment by RoiArthurB** [comment]
Fixed with commits e8c1b362cf5bf52e530eebc82ca8c46a6bf55e34 and 75acdeb56410fb67fe1e8fd19a109340a516e706
If it doesn't work on your computer, try to refresh your browser cache ( on the page you want to refresh the cache > `CTRL`+`SHIFT`+`R` )
