### ISSUE TITLE
error when moving from page to page in EN website

### ISSUE THREAD

**Issue by ClementineCttn** [covprehension/CoVprehension#15]
Dans la version EN du site, quand on passe de simulator à resources à about à simulator, ça aboutit parfois à des pages inexistantes https://en/simulateur ou bien ça renvoie vers le formulaire des questions en FR, alors que si on repasse toujours par la page d'accueil tout fonctionne bien

**Comment by RoiArthurB** [comment]
Comes from the same error than issue #14 ^^
