### ISSUE TITLE
JS Simulation's buttons doesn't switch language

### ISSUE THREAD

**Issue by RoiArthurB** [covprehension/CoVprehension#16]
**Describe the bug**
From: @benoitgaudou https://discordapp.com/channels/690125443952672780/691934314631266354/696931587501195324
> Dans les Q1-2-3, les simu en JS, il y a encore des textes dans les boutons en FR 🙂

**Related pages**
- https://covprehension.org/en/2020/03/24/q1.html
- https://covprehension.org/en/2020/03/24/q2.html
- https://covprehension.org/en/2020/03/24/q3.html

**Expected behavior**
Update with global lang

**Additional context**

**Comment by RoiArthurB** [comment]
Fixed here 36d6641
@ClementineCttn I let you translate the file `_i18n/en/simu-en.js` :wink:

**Comment by ClementineCttn** [comment]
done!
