### ISSUE TITLE
Reorganise repo to allow for images and simulators in different languages

### ISSUE THREAD

**Issue by ClementineCttn** [covprehension/CoVprehension#18]
Pour le moment, les images et simulateurs sont à la racine (?) et apparaissent en FR seulement. Maintenant qu'Arnaud nous a envoyé les versions traduites il faudrait que les posts pointent vers de nouveaux dossiers en fonction de la langue
merci

**Comment by ClementineCttn** [comment]
Ou bien... On peut juste nommer les images "_en" comme Arnaud vient de le faire et pointer vers elles plutôt que les originales. Ca me va

**Comment by RoiArthurB** [comment]
C'est juste une question d'organisation, mais je pense pas aller modifier le site pour changer des URL écritent à la main 😅

Du coup tout dépend de comment vous préférez vous organiser : 
- Soit vous choisissez de suivre une manière de nommer les fichiers pour éviter que ce soit le bordel
- Soit vous rangez tout dans des sous-dossiers (de la même manière que ce qu'on a fait pour la page `/about/`)

**Comment by arnban** [comment]
Salut les copains, voici ce que je propose :
- images : on met tout dans le dossier /img/posts/ avec l'extension _en pour chaque fichier image traduit. Si ce fichier avec extension n'existe pas c'est que l'image n'a pas besoin d'être traduite
- Simulateurs Netlogo inclus dans les pages : o ajoute 00 à l'index pour l'anglais, ce qui donne par exemple CoVprehension_Confinement_Q600 pour le simulateur de la Q6
- Simulateur central accessible depuis le menu : je ne vois pas comment modifier le simulateur central pour la version anglaise à partir du fichier CoVprehension_En.html que je viens de charger dans le dossier /simulations/ ==> C'est plus tricky, genre faut passer par _includes/ ?

**Comment by RoiArthurB** [comment]
La question est réglée? Si oui vous pouvez fermer l'issue :)
