### ISSUE TITLE
Building website locally doesn't work

### ISSUE THREAD

**Issue by helenea** [covprehension/CoVprehension#28]
En suivant la procédure du README ça ne fonctionne pas sous Ubuntu :disappointed: 

- Problème avec `bundle install` (je n'ai pas les bons logs parce que je n'avais pas encore ruby d'installé à ce moment là...)
@romainreuillon a trouvé la solution de lancer `bundle config set path $HOME/.ruby/bundles/` puis `bundle install --path bundles/`pour que ça fonctionne

- Problème avec `bundle exec jekyll serve`
```Configuration file: /home/helene/Documents/CoVprehension/website/_config.yml
            Source: /home/helene/Documents/CoVprehension/website
       Destination: /home/helene/Documents/CoVprehension/website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Building site for default language: "fr" to: /home/helene/Documents/CoVprehension/website/_site
             Error: could not read file /home/helene/Documents/CoVprehension/website/bundles/ruby/2.5.0/gems/jekyll-3.8.6/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'bundles/ruby/2.5.0/gems/jekyll-3.8.6/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'bundles/ruby/2.5.0/gems/jekyll-3.8.6/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```

En me basant sur cette [issue](https://github.com/jekyll/jekyll/issues/2938) j'ai rajouté `exclude : [bundles]` dans _config.yml et j'ai pu lancer le site. J'ai aussi trouvé ce [lien](https://jekyllrb.com/docs/troubleshooting/#configuration-problems) vers Jekyll mais je m'y connais pas assez pour comprendre de quoi ça parle, surtout que ce n'est pas exactement le même problème (eux c'est avec vendor, nous c'est avec bundles).

- Problème une fois le site lancé : dès que je fais un changement sur un fichier je dois fermer la machine, supprimer le dossier _site qui a été créé et relancer la machine :sweat_smile: Les logs quand la machine est lancée : 
```Configuration file: /home/helene/Documents/CoVprehension/website/_config.yml
            Source: /home/helene/Documents/CoVprehension/website
       Destination: /home/helene/Documents/CoVprehension/website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Building site for default language: "fr" to: /home/helene/Documents/CoVprehension/website/_site
       Jekyll Feed: Generating feed for posts
Loading translation from file /home/helene/Documents/CoVprehension/website/_i18n/fr.yml
Building site for language: "en" to: /home/helene/Documents/CoVprehension/website/_site/en
       Jekyll Feed: Generating feed for posts
Loading translation from file /home/helene/Documents/CoVprehension/website/_i18n/en.yml
Build complete
                    done in 1.467 seconds.
 Auto-regeneration: enabled for '/home/helene/Documents/CoVprehension/website'
    Server address: http://127.0.0.1:4000//
  Server running... press ctrl-c to stop.
[2020-04-14 17:58:59] ERROR `/assets/lang/simu-fr.js' not found.
[2020-04-14 17:58:59] ERROR `/assets/lang/simu-fr.js' not found.
      Regenerating: 1 file(s) changed at 2020-04-14 17:59:49
                    _i18n/fr/_posts/2020-04-01-q8.md
Building site for default language: "fr" to: /home/helene/Documents/CoVprehension/website/_site
       Jekyll Feed: Generating feed for posts
Loading translation from file /home/helene/Documents/CoVprehension/website/_i18n/fr.yml
             Error: File exists @ syserr_fail2_in - /home/helene/Documents/CoVprehension/website/_site/assets/lang/simu-en.js
             Error: Run jekyll build --trace for more information.
                    
      Regenerating: 1 file(s) changed at 2020-04-14 18:00:34
                    _i18n/fr/_posts/2020-04-01-q8.md
Building site for default language: "fr" to: /home/helene/Documents/CoVprehension/website/_site
       Jekyll Feed: Generating feed for posts
Loading translation from file /home/helene/Documents/CoVprehension/website/_i18n/fr.yml
             Error: File exists @ syserr_fail2_in - /home/helene/Documents/CoVprehension/website/_site/assets/lang/simu-en.js
             Error: Run jekyll build --trace for more information.
```

**Comment by RoiArthurB** [comment]
Salut, Je vais essayer de répondre point par point :

**Réponse**

> - Problème avec `bundle install`

Bundle est juste un package manager pour Ruby qui permet de gérer l'installation des différents plugins (doc de bundle relative à jekyll ici : https://jekyllrb.com/tutorials/using-jekyll-with-bundler/ )

Techniquement, cette commande ne devrait pas poser de problème car elle est utilisée à chaque compilation du site dans le Github Action (qui ne garde pas de cache) https://github.com/covprehension/CoVprehension/blob/master/.github/workflows/jekyll.yml#L33-L34 🤔

> - Problème avec `bundle exec jekyll serve`

Je pense que c'est à cause du bundle install

> J'ai aussi trouvé ce lien vers Jekyll mais je m'y connais pas assez pour comprendre de quoi ça parle, surtout que ce n'est pas exactement le même problème (eux c'est avec vendor, nous c'est avec bundles).

Ça a rien à voir. Le problème décrit dans le lien serait pour des dossiers à la racine qui s'appelle `/vendor/` (utilisé pour les lib PHP/JS) et/ou `/node-module/` (utilisé pour les lib NodeJS). Nous tout est caché dans des sous-dossier donc ça devrait pas poser de pb 😀

> - Problème une fois le site lancé : dès que je fais un changement sur un fichier je dois fermer la machine, supprimer le dossier _site qui a été créé et relancer la machine :sweat_smile:

A chaque modif le site met 2s (environ) pour se régénérer entièrement. Je vois dans tes logs que le site se régénère automatiquement... 
```
 Auto-regeneration: enabled for '/home/helene/Documents/CoVprehension/website'
```
Si vraiment le site ne se régénère pas, essaye de rajouter le flag `--incremental` (comme suggéré dans tes logs une fois encore) qui devrait éviter une re-compilation entière du site mais juste des fichiers modifier 🤷

**Discussion**

En tout cas, tout ça est très bizarre et je n'ai eu aucun problème de la sorte sur mon installation locale.... 🤔

Globalement je pense que le problème vient de l'utilisation de _Bundle_ qui a créée des pbs dès le départ. Il doit être mal installé/configuré qqp et les appels en Ruby doivent bugger à cause de ça. En tout cas c'est la solution la plus plausible que je vois 🤷

**Comment by helenea** [comment]
Même avec `--incremental` la regénération ne fonctionne pas.

```Configuration file: /home/helene/Documents/CoVprehension/website/_config.yml
            Source: /home/helene/Documents/CoVprehension/website
       Destination: /home/helene/Documents/CoVprehension/website/_site
 Incremental build: enabled
      Generating... 
Building site for default language: "fr" to: /home/helene/Documents/CoVprehension/website/_site
       Jekyll Feed: Generating feed for posts
Loading translation from file /home/helene/Documents/CoVprehension/website/_i18n/fr.yml
Building site for language: "en" to: /home/helene/Documents/CoVprehension/website/_site/en
             Error: YAML Exception reading /home/helene/Documents/CoVprehension/website/_i18n/en/_posts/2020-04-08-q13.md: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1
       Jekyll Feed: Generating feed for posts
Loading translation from file /home/helene/Documents/CoVprehension/website/_i18n/en.yml
Build complete
                    done in 2.386 seconds.
 Auto-regeneration: enabled for '/home/helene/Documents/CoVprehension/website'
    Server address: http://127.0.0.1:4000//
  Server running... press ctrl-c to stop.
[2020-04-15 10:43:54] ERROR `/assets/lang/simu-fr.js' not found.
[2020-04-15 10:43:54] ERROR `/assets/lang/simu-fr.js' not found.
      Regenerating: 1 file(s) changed at 2020-04-15 10:44:47
                    _i18n/fr/_posts/2020-04-01-q8.md
Building site for default language: "fr" to: /home/helene/Documents/CoVprehension/website/_site
       Jekyll Feed: Generating feed for posts
Loading translation from file /home/helene/Documents/CoVprehension/website/_i18n/fr.yml
             Error: File exists @ syserr_fail2_in - /home/helene/Documents/CoVprehension/website/_site/assets/lang/simu-en.js
             Error: Run jekyll build --trace for more information.
                    
[2020-04-15 10:45:04] ERROR `/assets/lang/simu-fr.js' not found.
[2020-04-15 10:45:05] ERROR `/assets/lang/simu-fr.js' not found.
```

**Comment by RoiArthurB** [comment]
Ok essayons de décortiquer le log ensemble pour comprendre à quel moment ça coince (parce que j'suis pas sûr de comprendre) : 
> ```
>            Source: /home/helene/Documents/CoVprehension/website
>       Destination: /home/helene/Documents/CoVprehension/website/_site
> Incremental build: enabled
>```
Ok donc là on a nos input/output qui sont pas bons déjà... Je sais pas quelle commande tu utilises mais normalement il devrait y avoir une première ligne avec le fichier de config, mais vu que le reste fonctionne je pense que c'est juste un mauvais copié-collé.

Dans le doute voilà le mien : 
```
$ bundle exec jekyll serve
Configuration file: /home/roiarthurb/Documents/Dev/CoVprendre/_config.yml
            Source: /home/roiarthurb/Documents/Dev/CoVprendre
       Destination: /home/roiarthurb/Documents/Dev/CoVprendre/_site
 Incremental build: disabled. Enable with --incremental
```

> ```
>       Generating... 
> Building site for default language: "fr" to: /home/helene/Documents/CoVprehension/website/_site
>        Jekyll Feed: Generating feed for posts
> Loading translation from file /home/helene/Documents/CoVprehension/website/_i18n/fr.yml
> Building site for language: "en" to: /home/helene/Documents/CoVprehension/website/_site/en
>              Error: YAML Exception reading /home/helene/Documents/CoVprehension/website/_i18n/en/_posts/2020-04-08-q13.md: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1
>        Jekyll Feed: Generating feed for posts
> Loading translation from file /home/helene/Documents/CoVprehension/website/_i18n/en.yml
> Build complete
>                     done in 2.386 seconds.
>  Auto-regeneration: enabled for '/home/helene/Documents/CoVprehension/website'
>```

Donc là on a tout le site qui a été généré proprement en français et en anglais (il y a un problème dans le post 13 en anglais, mais c'est pas bloquant normalement, juste un problème dans le _Front Matter_).

>```
>     Server address: http://127.0.0.1:4000//
>   Server running... press ctrl-c to stop.
> ```

Là le site est accessible via l'URL http://127.0.0.1:4000/

> ```
> [2020-04-15 10:43:54] ERROR `/assets/lang/simu-fr.js' not found.
> [2020-04-15 10:43:54] ERROR `/assets/lang/simu-fr.js' not found.
> ```

Là je devine que tu as navigué sur 2 post en français. J'ai oublié de mettre la commande dans le README mais il faut rentrer la commande suivante (qui est faite dans le build mais que j'ai placé là pour simplifier l'arborescence pour la traduction)
```
rm -f assets/lang/*.js && cp _i18n/*/simu-*.js assets/lang/
```

Mais pareil, juste un fichier pas servi par le serveur, c'est pas une erreur bloquante.

> ```
>       Regenerating: 1 file(s) changed at 2020-04-15 10:44:47
>                     _i18n/fr/_posts/2020-04-01-q8.md
> ```

Là tu as modifié le fichier `_i18n/fr/_posts/2020-04-01-q8.md`

> ```
> Building site for default language: "fr" to: /home/helene/Documents/CoVprehension/website/_site
>        Jekyll Feed: Generating feed for posts
> Loading translation from file /home/helene/Documents/CoVprehension/website/_i18n/fr.yml
> ```

Le site ne régénère que la partie nécessaire (soit une page en français et le feed RSS)

> ```
>              Error: File exists @ syserr_fail2_in - /home/helene/Documents/CoVprehension/website/_site/assets/lang/simu-en.js
>              Error: Run jekyll build --trace for more information.
> ```

La seule erreure qu'est un conflit entre 2 fichiers.. Problème étant que ce fichier n'est pas censé existé (parce que celui en français n'existe pas)... Est-ce que tu pourrais me dire s'il existe et si oui ce qu'il contient ?

Tu peux aussi rajouter le flag `--trace` qui stop tout et affiche un log plus complet lors d'_error_

> ```
>                     
> [2020-04-15 10:45:04] ERROR `/assets/lang/simu-fr.js' not found.
> [2020-04-15 10:45:05] ERROR `/assets/lang/simu-fr.js' not found.
> ```

La même erreur qu'avant de fichier non-servi

**Conclusion**

Je sais pas trop ce qui ne fonctionne pas, la seule vraie erreur (le conflit entre les fichiers) n'a même pas de lien avec la partie du site en français. 

Mais du coup le problème là c'est que le contenu de la page ne se met pas à jour quand tu la modifies c'est bien ça ? Même en rafraichissant la page simplement (F5 ou Ctrl + R) et en rafraichissant sans le cache du navigateur (Ctrl + Shift + R) ça fonctionne ?

**Comment by helenea** [comment]
En exécutant `rm -f assets/lang/*.js && cp _i18n/*/simu-*.js assets/lang/` je n'ai plus d'erreurs et la regénération fonctionne =D

**Comment by RoiArthurB** [comment]
Ah ! Du coup c'était un vrai problème ça. Pour moi c'était pas un bug bloquant à la compilation ^^"

Du coup j'ai rajouté ça dans le README (eefd51ad3f59d490c0a93fd6c4581774adf4b202) déjà, mais le pb avec _Bundler_ est pas vraiment réglé même si y a un workaround... 😕

**Comment by RoiArthurB** [comment]
Bon.. J'ai cherché pendant une bonne poignée d'heure et mise à part le problème d'installation de _Bundler_ j'ai rien trouvé...

Je ferme l'issue en "won't fix" du coup, mais si vous avez à nouveau le pb on peut la ré-ouvrir 😀
