### ISSUE TITLE
Posts list pages

### ISSUE THREAD

**Issue by helenea** [covprehension/CoVprehension#46]
A few minor problems with the new posts list and the buttons at the end of the pages: 
- on the main page, button should probably be "older questions" now, instead of "latest"
- on /posts page, there is no left button to go back to the latest questions (i.e. the main page)
- English version, /posts/3 is empty (but I guess it's because previews are shorter in English than in French)

Additional remark: is there a way to easily add unbreakable spaces in markdown (other than the tedious "\&nbsp;")? The spaces before ":" and "?" should be unbreakable in French if we don't want this to happen:

![image](https://user-images.githubusercontent.com/8794131/80945322-da72a980-8deb-11ea-941e-062e7c32c511.png)

**Comment by RoiArthurB** [comment]
Many issues in your post, I'll split it :)

**Comment by RoiArthurB** [comment]
> Additional remark: is there a way to easily add unbreakable spaces in markdown (other than the tedious "&nbsp;")? The spaces before ":" and "?" should be unbreakable in French if we don't want this to happen:

Yes, you can add a non-breaking space ` ` ( https://stackoverflow.com/a/54174466/6284933 )

> | System     | Key combination                                             |
> |------------|-------------------------------------------------------------|
> | macOS      | <kbd>⌥ Opt</kbd>+<kbd>Space</kbd>                          |
> | Linux      | <kbd>Compose</kbd>+<kbd>Space</kbd>+<kbd>Space</kbd>        |
> | Windows    | <kbd>Alt</kbd>+<kbd>0</kbd>+<kbd>1</kbd>+<kbd>6</kbd>+<kbd>0</kbd> or |                
> |            | <kbd>Alt</kbd>+<kbd>2</kbd>+<kbd>5</kbd>+<kbd>5</kbd>       |
> | In many commercial software | <kbd>Ctrl</kbd>+<kbd>Space</kbd>           |
